FROM node:alpine as build

WORKDIR /app
COPY ./react-app .
RUN yarn
RUN yarn build

FROM nginx:alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
